name: Dependency Update

on:
  schedule:
    - cron: '0 2 * * MON'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Update dependencies
      run: |
        npx npm-check-updates -u
        npm install
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Automated Dependency Update'
        body: |
          ## 🔄 Dependency Update
          
          This PR updates all dependencies to their latest versions.
          
          ### Changes
          - Updated package.json dependencies
          - Ran tests to ensure compatibility
          
          ### Testing
          - [ ] All tests pass
          - [ ] No breaking changes detected
          
          **Auto-generated by GitHub Actions** 🤖
        branch: dependencies/auto-update
        labels: dependencies, maintenance
